 CREATE OR REPLACE PROCEDURE DELETE_CLIENTE(
  C_CEDULA IN CLIENTE.Cedula%TYPE,
   C_RESULT OUT VARCHAR2
 )
 AS
 BEGIN
   DELETE FROM CLIENTE
   WHERE Cedula = C_CEDULA;
  C_RESULT:= 'SE ELIMINÓ CORRECTAMENTE EL CLIENTE';
  COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
          C_RESULT:= 'ERROR AL ELIMINAR'; 
        ROLLBACK;  
 END;
 
 
 CREATE TABLE cliente (
Cedula VARCHAR2(11) PRIMARY KEY,
PrimerNombre VARCHAR2(25),
SegundoNombre VARCHAR2(25),
PrimerApellido VARCHAR2(25),
SegundoApellido VARCHAR2(25),
Telefono VARCHAR2(10),
Email VARCHAR2(50),
Marca VARCHAR2(50),
Modelo VARCHAR2(10),
TipoAceite VARCHAR2(25),
ReferenciaAceite VARCHAR2(50),
TipoFiltro VARCHAR2(50),
ReferenciaFiltro VARCHAR2(50)
);
    
  CREATE OR REPLACE PROCEDURE UPDATE_CLIENTE(
 P_DNI IN CLIENTE.DNI%TYPE,
 P_NOMBRE IN  CLIENTE.NOMBRE%TYPE,
 P_APELLIDO IN CLIENTE.APELLIDO%TYPE,
 P_EMAIL IN CLIENTE.EMAIL%TYPE,
 P_TELEFONO IN CLIENTE.TELEFONO%TYPE,
 P_RESULT OUT VARCHAR2
 )
 AS
 BEGIN 
   UPDATE CLIENTE
   SET NOMBRE = P_NOMBRE, APELLIDO=P_APELLIDO,EMAIL=P_EMAIL,TELEFONO=P_TELEFONO
   WHERE DNI= P_DNI;
   P_RESULT:= 'SE EJECUTO CORRECTAMENTE';
   COMMIT;
   EXCEPTION
     WHEN OTHERS THEN
        P_RESULT:= 'ERROR AL ACTUALIZAR'; 
        ROLLBACK; 
 END;
 
 
 select * from cliente;
 
 
 
  CREATE OR REPLACE PROCEDURE SELECT_CLIENTE_ID(
  C_CEDULA IN CLIENTE.Cedula%TYPE,
 C_CURSOR OUT  SYS_REFCURSOR
 )
 AS
 BEGIN
   OPEN C_CURSOR FOR
   SELECT CEDULA ,
PRIMERNOMBRE ,
SEGUNDONOMBRE ,
PRIMERAPELLIDO ,
SEGUNDOAPELLIDO ,
TELEFONO ,
EMAIL ,
DIRECCION ,
EDAD ,
CIUDAD ,
COMUNA ,
BARRIO ,
NACIONALIDAD     
    FROM CLIENTE WHERE Cedula = C_CEDULA;
 
   END;

